# Generated by Django 5.2.3 on 2025-07-02 08:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmmSpecialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('photo', models.ImageField(upload_to='specialist_photo/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание опыта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'SMM специалист',
                'verbose_name_plural': 'SMM специалисты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Уникальный токен')),
                ('client_name', models.CharField(max_length=100, verbose_name='Названия бизнеса')),
                ('id_user', models.BooleanField(default=False, verbose_name='был ли использован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда создан')),
                ('smm_specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smm_specialists.smmspecialist', verbose_name='Кому отзыв')),
            ],
            options={
                'verbose_name': 'Токен отзыва',
                'verbose_name_plural': 'Токены отзывав',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Название бизнеса')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('comment', models.TextField(verbose_name='текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('smm_specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smm_specialists.smmspecialist', verbose_name='кому отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
