# Generated by Django 5.2.3 on 2025-07-02 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smm_specialists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewtoken',
            old_name='id_user',
            new_name='is_user',
        ),
    ]
